### ISSUE TITLE
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #3 'index' upgrade to torch 1.0.1 

### ISSUE THREAD

**Issue by belerico** [anhaidgroup/deepmatcher#20]
After upgrade to torch==1.0.1 and torchtext>=0.2.3 I receive the following error. Is there a way I can fix it? I've to setting device to the possible modules in question but nothing had worked
```
Traceback (most recent call last):
  File "matching.py", line 42, in <module>
    model.initialize(train)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/src/deepmatcher/deepmatcher/models/core.py", line 357, in initialize
    self.forward(init_batch)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/src/deepmatcher/deepmatcher/models/core.py", line 421, in forward
    embeddings[name] = self.embed[name](attr_input)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/src/deepmatcher/deepmatcher/models/modules.py", line 187, in forward
    results = self.module(*module_args)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/belerico/.local/share/virtualenvs/ceneje_prodmatch-Z0l7suQy/lib/python3.6/site-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #3 'index'
```

**Comment by belerico** [comment]
https://github.com/belerico/deepmatcher/tree/torch_1.0.1
