### ISSUE TITLE
NaN detected - what could have gone wrong?

### ISSUE THREAD

**Issue by ziqizhang** [anhaidgroup/deepmatcher#76]
Hello

I am running DM on a dataset and I get this error that causes the program to abort. I have no clue where to look. Because the same dataset is ok when used by another algorithm. I would appreciate some insights into this.

The output looks like this:

```
........
===>  TRAIN Epoch 18
Warning: No valid output stream.
Finished Epoch 18 || Run Time:  248.8 | Load Time:  106.4 || F1:  98.11 | Prec:  98.48 | Rec:  97.73 || Ex/s:  20.35

===>  EVAL Epoch 18
Warning: No valid output stream.
Finished Epoch 18 || Run Time:   25.5 | Load Time:   24.4 || F1:  58.34 | Prec:  63.61 | Rec:  53.88 || Ex/s:  36.27

---------------------

===>  TRAIN Epoch 19
Warning: No valid output stream.
Finished Epoch 19 || Run Time:  248.0 | Load Time:  106.1 || F1:  98.40 | Prec:  98.64 | Rec:  98.17 || Ex/s:  20.42

===>  EVAL Epoch 19
Warning: No valid output stream.
Finished Epoch 19 || Run Time:   25.3 | Load Time:   24.2 || F1:  57.93 | Prec:  62.07 | Rec:  54.31 || Ex/s:  36.56

---------------------

===>  TRAIN Epoch 20
Warning: No valid output stream.
Finished Epoch 20 || Run Time:  247.0 | Load Time:  105.7 || F1:  98.65 | Prec:  98.86 | Rec:  98.44 || Ex/s:  20.50

===>  EVAL Epoch 20
Warning: No valid output stream.
Finished Epoch 20 || Run Time:   25.3 | Load Time:   24.2 || F1:  57.46 | Prec:  59.95 | Rec:  55.17 || Ex/s:  36.53

---------------------

===>  EVAL Epoch 20
Warning: No valid output stream.
Finished Epoch 20 || Run Time:   25.3 | Load Time:   24.2 || F1:  57.46 | Prec:  59.95 | Rec:  55.17 || Ex/s:  36.53

---------------------

===>  TRAIN Epoch 21
Warning: No valid output stream.
NaN detected!!!
> /home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/_utils.py(42)check_nan()
-> for value in values:
(Pdb) Traceback (most recent call last):
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/li1zz/wop_matching/src/exp/run_dm_standard.py", line 107, in <module>
    best_save_path=ourput_dir+"/best_model.pth"
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/core.py", line 183, in run_train
    return Runner.train(self, *args, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/runner.py", line 339, in train
    'TRAIN', model, train_dataset, criterion, optimizer, train=True, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/runner.py", line 214, in _run
    output = model(batch)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/core.py", line 425, in forward
    embeddings[right])
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/modules.py", line 122, in forward
    return self._forward(input, *args, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/core.py", line 546, in _forward
    left_aggregated = self.word_aggregator(left_compared, left_aggregator_context)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/modules.py", line 122, in forward
    return self._forward(input, *args, **kwargs)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/word_aggregators.py", line 121, in _forward
    AttrTensor.from_old_metadata(context, context_with_meta))
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in __call__
    hook_result = hook(self, input, result)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/modules.py", line 152, in _check_nan_hook
    _utils.check_nan(*tensors)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/_utils.py", line 42, in check_nan
    for value in values:
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/deepmatcher/models/_utils.py", line 42, in check_nan
    for value in values:
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/li1zz/.conda/envs/tensorflow-gpu/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

**Comment by sidharthms** [comment]
Are the datasets that we shared working for you? Is it failing only on a specific dataset? Please share your code as a Colab notebook if you can.
