### ISSUE TITLE
array must not contain infs or NaNs

### ISSUE THREAD

**Issue by ksrinivas007** [anhaidgroup/deepmatcher#77]
Hi Guys
I am getting this numpy error
`Computing principal components
0% [######] 100% | ETA: 00:00:00
Total time elapsed: 00:00:01
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    run_experiment(model_name, dataset_dir, embedding_dir)
  File "run.py", line 16, in run_experiment
    datasets = dm.data.process(path=dataset_dir,
  File "/root/anaconda3/lib/python3.8/site-packages/deepmatcher/data/process.py", line 208, in process
    datasets = MatchingDataset.splits(
  File "/root/anaconda3/lib/python3.8/site-packages/deepmatcher/data/dataset.py", line 581, in splits
    datasets[0].compute_metadata(train_pca)
  File "/root/anaconda3/lib/python3.8/site-packages/deepmatcher/data/dataset.py", line 291, in compute_metadata
    svd.fit(concatenated.numpy())
  File "/root/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_truncated_svd.py", line 143, in fit
    self.fit_transform(X)
  File "/root/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_truncated_svd.py", line 178, in fit_transform
    U, Sigma, VT = randomized_svd(X, self.n_components,
  File "/root/anaconda3/lib/python3.8/site-packages/sklearn/utils/extmath.py", line 354, in randomized_svd
    Uhat, s, V = linalg.svd(B, full_matrices=False)
  File "/root/anaconda3/lib/python3.8/site-packages/scipy/linalg/decomp_svd.py", line 106, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/root/anaconda3/lib/python3.8/site-packages/scipy/_lib/_util.py", line 263, in _asarray_validated
    a = toarray(a)
  File "/root/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 485, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs`

Any suggestions please ?
Thanks
Sreeni

**Comment by sidharthms** [comment]
Is it possible to convert your code into a Colab notebook and share so I can take a look?

**Comment by tidianelyahmed** [comment]
Hi Guys
Did you solve this numpy error?
I have the same
