### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'float32'

### ISSUE THREAD

**Issue by andeek** [anhaidgroup/deepmatcher#8]
Hi I am attempting to use deepmatcher on Mac OS. I have installed using

`pip3 install deepmatcher`

which seems to have worked. 

```
Installing collected packages: torch, torchtext, deepmatcher
Successfully installed deepmatcher-0.1.0.post1 torch-0.3.1 torchtext-0.3.1
```

I am currently using 

```
python3 --version
Python 3.6.5
```

When attempting to load `deepmatcher` using `import deepmatcher as dm` I get the following error:

```
>>> import deepmatcher as dm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/deepmatcher/__init__.py", line 10, in <module>
    from .data import process as data_process
  File "/usr/local/lib/python3.6/site-packages/deepmatcher/data/__init__.py", line 1, in <module>
    from .field import MatchingField, reset_vector_cache
  File "/usr/local/lib/python3.6/site-packages/deepmatcher/data/field.py", line 11, in <module>
    from torchtext import data, vocab
  File "/usr/local/lib/python3.6/site-packages/torchtext/__init__.py", line 1, in <module>
    from . import data
  File "/usr/local/lib/python3.6/site-packages/torchtext/data/__init__.py", line 4, in <module>
    from .field import RawField, Field, ReversibleField, SubwordField, NestedField, LabelField
  File "/usr/local/lib/python3.6/site-packages/torchtext/data/field.py", line 61, in <module>
    class Field(RawField):
  File "/usr/local/lib/python3.6/site-packages/torchtext/data/field.py", line 118, in Field
    torch.float32: float,
AttributeError: module 'torch' has no attribute 'float32'
```

Any help would be greatly appreciated.

**Comment by andeek** [comment]
This looks related to 669f05f

**Comment by 0xNaN** [comment]
Hi, is there any news for this bug?
I'm trying to use `deepmatcher` running the getting started notebook with Google Colaboraty but it fails during the import of the project

https://colab.research.google.com/github/anhaidgroup/deepmatcher/blob/master/examples/getting_started.ipynb

**Comment by Stravanni** [comment]
> Hi, is there any news for this bug?
> I'm trying to use `deepmatcher` running the getting started notebook with Google Colaboraty but it fails during the import of the project
> 
> https://colab.research.google.com/github/anhaidgroup/deepmatcher/blob/master/examples/getting_started.ipynb

Just: pip install torchtext==0.2.3
(on colab: !pip install torchtext==0.2.3)

**Comment by walide67** [comment]
i got the same issue.
pip install torchtext==0.2.3
you need to change version of torchtext
